default_language_version.python = "3.14"

[[repos]]
repo = "local"
hooks = [
  {
    id = "ruff",
    name = "ruff",
    language = "system",
    entry = "python3 -m ruff check",
    files = "\\.py$",
  },
]
