default_language_version.python = "3.14"

[[repos]]
repo = "local"
hooks = [
  {
    id = "ruff",
    name = "ruff",
    language = "system",
    entry = "python3 -m ruff check",
    files = "\\.py$",
  },
  {
    id = "ruff-format",
    name = "ruff-format",
    language = "system",
    entry = "python3 -m ruff format",
    files = "\\.py$",
  },
]

[[repos]]
repo = "builtin"
hooks = [
  { id = "no-commit-to-branch", args = ["-b", "develop"] },
]
