"""Canonical wireframe.css generator.

Per ``docs/visual-design/design.md`` §"The wireframe.css — static
utility layer + greyscale tokens": one hand-curated stylesheet (~200-300
lines) covering the most-used Tailwind-shaped utility names, with
implementations driven by CSS custom properties. Wireframes use the
class names; the visual outcome is greyscale because of the variable
values.

The agent never edits this file — it's generated once at VD discovery
start. The transition wireframe → bones is "swap the variable values"
not "swap the stylesheet"; for MVP we ship the wireframe-mode values
inline. The MVP scope generator takes an optional ``DesignSystem`` and
overrides the color tokens from it (so the operator-supplied tokens
land at MVP layer).
"""
from __future__ import annotations

from jig.schemas.design_system import DesignSystem

__all__ = ["WIREFRAME_CSS", "generate_wireframe_css"]


# Hand-curated baseline stylesheet. Mirrors the design.md example one-
# for-one: greyscale variable values, then the small utility class set
# the wireframes use. Names match Tailwind conventions so the agent can
# lean on its existing training. Implementation via ``var(--*)`` so the
# bones-layer transition is a value swap.
WIREFRAME_CSS: str = """\
/* .jig/spec/wireframes/wireframe.css — generated by jig.wireframes.wireframe_css */

/* Greyscale token values — what makes this "wireframe mode" */
:root {
  --color-bg: #f5f5f5;
  --color-surface: #ffffff;
  --color-primary: #888888;
  --color-on-primary: #ffffff;
  --color-default: #2a2a2a;
  --color-muted: #888888;
  --color-border: #888888;
  --color-border-strong: #444444;

  --font-mono: ui-monospace, 'SF Mono', Menlo, monospace;
  --font-sans: var(--font-mono);

  --space-1: 4px; --space-2: 8px; --space-3: 12px; --space-4: 16px;
  --space-6: 24px; --space-8: 32px; --space-12: 48px;

  --text-xs: 11px; --text-sm: 13px; --text-base: 15px; --text-lg: 18px;
  --text-xl: 24px; --text-2xl: 32px;

  --radius-default: 0;
  --shadow-default: none;
}

/* Reset + base */
* { box-sizing: border-box; font-family: var(--font-mono); color: var(--color-default); }
body { margin: 0; background: var(--color-bg); }
small, .text-sm { font-size: var(--text-sm); color: var(--color-muted); }
input, textarea, select, button { font: inherit; color: inherit; }
input:disabled, textarea:disabled, select:disabled, button:disabled { opacity: 1; cursor: default; }

/* Color utilities — read from variables */
.bg-primary { background: var(--color-primary); }
.bg-surface { background: var(--color-surface); }
.text-on-primary { color: var(--color-on-primary); }
.text-muted { color: var(--color-muted); }
.text-default { color: var(--color-default); }

/* Layout utilities — Tailwind-shape names */
.flex { display: flex; }
.flex-row { display: flex; flex-direction: row; }
.flex-col { display: flex; flex-direction: column; }
.flex-1 { flex: 1; }
.grid { display: grid; }
.items-center { align-items: center; }
.items-start { align-items: flex-start; }
.justify-between { justify-content: space-between; }
.gap-1 { gap: var(--space-1); } .gap-2 { gap: var(--space-2); }
.gap-3 { gap: var(--space-3); } .gap-4 { gap: var(--space-4); } .gap-6 { gap: var(--space-6); }

/* Spacing — full Tailwind name set for the most-used scales */
.p-1 { padding: var(--space-1); } .p-2 { padding: var(--space-2); }
.p-3 { padding: var(--space-3); } .p-4 { padding: var(--space-4); } .p-6 { padding: var(--space-6); }
.px-2 { padding-left: var(--space-2); padding-right: var(--space-2); }
.px-4 { padding-left: var(--space-4); padding-right: var(--space-4); }
.py-2 { padding-top: var(--space-2); padding-bottom: var(--space-2); }
.mb-2 { margin-bottom: var(--space-2); } .mb-4 { margin-bottom: var(--space-4); } .mb-6 { margin-bottom: var(--space-6); }
.mt-4 { margin-top: var(--space-4); } .mt-6 { margin-top: var(--space-6); }

/* Sizing */
.w-full { width: 100%; } .h-full { height: 100%; }
.min-h-screen { min-height: 100vh; }
.max-w-md { max-width: 28rem; } .max-w-2xl { max-width: 42rem; } .max-w-4xl { max-width: 56rem; }
.h-32 { height: 8rem; }
.container { width: 100%; }
.mx-auto { margin-left: auto; margin-right: auto; }

/* Typography */
.text-xs { font-size: var(--text-xs); } .text-sm { font-size: var(--text-sm); }
.text-base { font-size: var(--text-base); } .text-lg { font-size: var(--text-lg); }
.text-xl { font-size: var(--text-xl); } .text-2xl { font-size: var(--text-2xl); }
.font-medium { font-weight: 500; } .font-semibold { font-weight: 600; } .font-bold { font-weight: 700; }
.italic { font-style: italic; } .underline { text-decoration: underline; }

/* Borders */
.border { border: 1px solid var(--color-border); }
.border-b { border-bottom: 1px solid var(--color-border); }
.border-t { border-top: 1px solid var(--color-border); }
.border-strong { border-color: var(--color-border-strong); }
.rounded { border-radius: var(--radius-default); }

/* Element-default styling for sketched look */
header, main, aside, footer, nav, section, article {
  outline: 1px dashed var(--color-border); background: var(--color-surface); padding: var(--space-4);
}
input, textarea, select { border: 1px solid var(--color-border-strong); background: var(--color-surface); padding: var(--space-2); }
button { border: 1px solid var(--color-border-strong); background: var(--color-surface); padding: var(--space-2) var(--space-4); }
.placeholder { background: repeating-linear-gradient(45deg, #eeeeee, #eeeeee 8px, #dddddd 8px, #dddddd 16px); }
.placeholder-image { aspect-ratio: 16 / 9; }
"""


def generate_wireframe_css(design_system: DesignSystem | None = None) -> str:
    """Produce the wireframe.css content.

    With no ``design_system`` argument, returns the baseline greyscale
    stylesheet (``WIREFRAME_CSS`` constant). When a design system is
    passed, the color/spacing/type/shadow/border-radius variable values
    in the ``:root`` block are overridden from the system's tokens.
    The utility classes themselves stay identical — that's the whole
    point of the value-swap-not-stylesheet-swap transition.

    For MVP this implementation does a targeted variable substitution
    rather than re-emitting the whole file. The substitution looks for
    the ``--<token-id>: <old>;`` pattern in the baseline and rewrites
    the value when the token id matches. Token ids that aren't already
    in the baseline are appended into ``:root`` so the operator's
    extensions land in scope.
    """
    if design_system is None:
        return WIREFRAME_CSS

    css = WIREFRAME_CSS
    extras: list[str] = []

    for token in design_system.tokens.tokens:
        # Map the token id to its CSS variable name. Token ids in the
        # default set already match the variable suffixes (``color-bg``
        # → ``--color-bg``); operator-supplied tokens follow the same
        # convention by contract.
        var_name = f"--{token.id}"
        # Tokenize on ``var_name: ... ;`` to do a targeted replacement
        # without affecting the surrounding declarations.
        marker = f"{var_name}:"
        idx = css.find(marker)
        if idx == -1:
            extras.append(f"  {var_name}: {token.value};")
            continue
        end = css.find(";", idx)
        if end == -1:
            # Defensive: malformed baseline (shouldn't happen since we
            # author it ourselves). Append to extras rather than raise
            # so a single broken declaration doesn't blow up the whole
            # generator.
            extras.append(f"  {var_name}: {token.value};")
            continue
        css = css[:idx] + f"{var_name}: {token.value}" + css[end:]

    if extras:
        # Splice extras into the existing :root block just before its
        # closing brace. The baseline always has exactly one :root
        # block; this is the simplest seam we can rely on without
        # bringing in a CSS parser.
        marker = "\n}"
        # Find the end of the FIRST closing brace after ``:root {`` —
        # that's the :root block we authored. Subsequent } belong to
        # other selectors.
        root_idx = css.find(":root {")
        if root_idx != -1:
            close_idx = css.find("\n}", root_idx)
            if close_idx != -1:
                css = (
                    css[:close_idx]
                    + "\n"
                    + "\n".join(extras)
                    + css[close_idx:]
                )
    return css
